### ISSUE TITLE
Renamed colonies appear with their old names

### ISSUE THREAD

**Issue by boterham** [benreid24/Stellaru#39] opened 2020-10-24 19:45 UTC
Renamed colonies are listed by their old names in graphs such as colony size/stability/etc.

**Comment by benreid24** [comment] 2020-10-24 20:37
There's two name fields in the game save for each planet, guess I picked the wrong one. Thanks for bringing this up!

**Comment by benreid24** [comment] 2020-10-24 20:52
Checked it out a bit. The two fields in the game save for planet names are `name` and `custom_name`. The former is the name itself and the latter is either a "yes" or "no". The frontend selects the most recent name available when determining the label for a planet on the chart. Was the game saved since changing the planet name?

**Comment by boterham** [comment] 2020-10-25 07:22
I did save the game afterwards. Restarting both Stellaris and Stellaru did not fix it either.

**Comment by benreid24** [comment] 2020-10-26 17:37
Did you use the same version of Stellaru when reinstalling?

**Comment by benreid24** [comment] 2020-10-28 23:25
I cannot reproduce and the issue appears resolved, so I will close this for now. Please reopen if it occurs again

**Closed by benreid24** 2020-10-28 23:25 UTC
Labels: bug
