### ISSUE TITLE
Stellaru fails to open the second time

### ISSUE THREAD

**Issue by Madiwka4** [benreid24/Stellaru#64] opened 2020-11-24 08:36 UTC
After launching Stellaru once and restarting, it gives an error for a second and the window closes. After trying to run it via PowerShell in order to see the output, I get:
`django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django.templatetags.i18n': No module named 'django.templatetags.i18n'`

FULL OUTPUT: 
`daphne\server.py:11: UserWarning: Something has already installed a non-asyncio Twisted reactor. Attempting to uninstall it; you can fix this warning by importing daphne.server early in your codebase or finding the package that imports Twisted and importing it later on.
Traceback (most recent call last):
  File "django\template\library.py", line 317, in import_library
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django.templatetags.i18n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "channels\staticfiles.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "channels\http.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "django\core\handlers\base.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "django\core\handlers\exception.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "django\views\debug.py", line 22, in <module>
  File "django\template\engine.py", line 51, in __init__
  File "django\template\engine.py", line 93, in get_template_libraries
  File "django\template\library.py", line 319, in import_library
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django.templatetags.i18n': No module named 'django.templatetags.i18n'
[18780] Failed to execute script main`

**Comment by benreid24** [comment] 2020-11-24 14:15
Will try to reproduce. Is Stellaru fully unzipped and copied somewhere? What version are you running?

**Comment by Madiwka4** [comment] 2020-11-24 14:24
I am running the latest Windows release. I unzipped it into a folder in the Downloads directory. 

It also appears that if I unzip an another copy into a different directory, it works, and all the data is saved.

**Comment by benreid24** [comment] 2020-11-24 14:57
Thanks for the information, will try to reproduce

**Comment by benreid24** [comment] 2020-11-26 02:29
I have tried to reproduce with several published versions but have not been able to. It looks like the error was due to a corrupted copy of Stellaru. I will hold this open for a while in case it happens again or if anyone else reports the error, then I will close it

**Comment by benreid24** [comment] 2021-03-02 16:11
It's been a while with no recurrence of this so I am going to close for now. We can reopen if it comes up again

**Closed by benreid24** 2021-03-02 16:11 UTC
Labels: bug
